n=int(input())
if n%2!=0:
    i=1
    n=n/2+1
    while i<=n:
        spaces=1
        while spaces<=n-i:
            print(' ',end='')
            spaces+=1
        star1=1
        star2=i
        while star1<=i:
            print('*',end='')
            star1+=1
            star2+=1
        star1=1
        star2=2*i-2
        while star1<=i-1:
            print('*',end='')
            star2-=1
            star1+=1         
        print()
        i+=1
    i=n-1
    while i>=1:
        spaces=1
        while spaces<=n-i:
            print(' ',end='')
            spaces+=1
        star1=1
        star2=i
        while star1<=i:
            print('*',end='')
            star1+=1
            star2+=1
        star1=1
        star2=2*i-2
        while star1<=i-1:
            print('*',end='')
            star2-=1
            star1+=1         
        print()
        i-=1    